server:
  port: 9000
  netty:
    connection-timeout: 2s # 1)
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: polar-keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI:http://localhost:8080}/realms/PolarBookshop
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000 # 1)
            response-timeout: 5s
            pool:
              type: elastic
              max-idle-time: 15s
              max-life-time: 60s
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                series: SERVER_ERROR
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
                  requestedTokens: 1
            - SaveSession
          routes:
            - id: catalog-route
              uri: ${CATALOG_SERVICE_URL:http://localhost:9001}
              predicates:
                - Path=/books/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: catalogCircuitBreaker
                    fallbackUri: forward:/catalog-fallback
            - id: order-route
              uri: ${ORDER_SERVICE_URL:http://localhost:9002}
              predicates:
                - Path=/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
            - id: spa-route
              uri: ${SPA_URL:http://localhost:9004}
              predicates:
                - Path=/,/*.css,/*.js,/favicon.ico
  data:
    redis:
      connect-timeout: 2000
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s # Можно использовать суффикс s
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s # Сделал чуть больше, чем response-timeout (5s)

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

#logging:
#  level:
#    io.github.resilience4j: DEBUG
#    org.springframework.cloud.gateway: DEBUG